# Site settings

# The repository this documentation is for.
# This will be used to automatically
# pull data like the title, tagline,
# and repository url.
repository: yuloh/parang

# The color scheme to use for syntax highlighting.
# The available color schemes are listed in
# the _includes/css/syntax directory.
syntax_theme: monokai
